on:
  workflow_call:

jobs:
  check-release-type:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        name: Get PR Type
        id: get-release
        with:
          script: |
            const { title } = context.payload.pull_request
            if (!title.includes("INC") && !title.includes("CHG")) {
              const errorMessage = `PR does not include an INC Number or a CHG Number`
              core.error(errorMessage)
              throw new Error(errorMessage)
            }
            if (title.includes("INC")) {
              const regex = /INC-\d+/;
              const result = title.match(regex);
              core.setOutput("type", "incident")
              core.setOutput("incident-number", result[0])
            }
            if (title.includes("CHG")) {
              const regex = /CHG-\d+/;
              const result = title.match(regex);
              core.setOutput("change-request-number", result[0])
              core.setOutput("type", "change-request")
            }
      - name: Send Release Type
        uses: actions/github-script@v7
        with:
          script: |
            const releaseType = "${{ steps.get-release.outputs.type }}"
            if (releaseType != "incident" || releaseType != "change-request") {
              throw new Error("Release Type not found")
            }

            if (releaseType == "incident") {
              const incidentNumber = "${{ steps.get-release.outputs.incident-number }}"
              console.log(`Send API Request to Service Now to Add a PR Number/URL to the Incident: ${incidentNumber}`)
            }

            if (releaseType == "change-request") {
              const changeRequestNumber = "${{ steps.get-release.outputs.change-request-number }}"
              console.log(`Send API Request to Service Now to Add a PR Number/URL to the Change Request ${changeRequestNumber}`)
            }
