on:
  workflow_call:

jobs:
  check-release-type:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        name: Get PR Type
        id: get-pr-type
        with:
          script: |
            const { title } = context.payload.pull_request
            if (!title.includes("INC") && !title.includes("CHG")) {
              const errorMessage = `PR does not include an INC Number or a CHG Number`
              core.error(errorMessage)
              throw new Error(errorMessage)
            }
            if (title.includes("INC")) {
              core.setOutput("type", "incident")
            }
            if (title.includes("CHG")) {
              core.setOutput("type", "change-request")
            }
      - name: Send Release Type
        uses: actions/github-script@v7
        with:
          script: |
            const releaseType = "${{ steps.get-pr-type.outputs.type }}"
            if (releaseType != "incident" && releaseType != "change-request") {
              throw new Error(`${releaseType} Release Type not found`)
            }

            if (releaseType == "incident") {
              console.log("Send API Request to Service Now to Add a PR Number/URL to the Incident")
            }

            if (releaseType == "change-request") {
              console.log("Send API Request to Service Now to Add a PR Number/URL to the Change Request")
            }
