on:
  workflow_call:

jobs:
  check-release-type:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            console.log(JSON.stringify(context))
            console.log('------------------------\n\n\n')
            console.log(JSON.stringify(context.payload.pull_request))
